### PR TITLE
fix: reset the registries

### PR DESCRIPTION
**Pull request by owulveryck**

### CODE REVIEW

**Comment by owulveryck** [comment]
This should fix #466

**Comment by dcu** [comment]
this fixes and issue I was struggling with, thanks Olivier

**Comment by dcu** [comment]
is it possible to write a test for this ?

**Comment by owulveryck** [comment]
> is it possible to write a test for this ?

I agree with you, I'd like to write a test before actually merging the PR.
It is easy to reproduce with agogo  (see https://github.com/gorgonia/agogo/blob/ce6073931e2c36f2986cd1048fc89ceb80c7df7a/dualnet/dual_test.go#L17) but the graph is big, and it is not easy to find the root cause.
I am still investigating.

**Comment by chewxy** [comment]
This is straightforwards and correct IMO.

**Pull request merged**
