### PR TITLE
[fix] Using the iterator of the new Gonum API

### PR DESCRIPTION
**Pull request by owulveryck**
This change allows the v0.9.2-working2 branch to compile and work with the latest evolution of the Gonum API.
The implementation relies on the [OrderedNode](https://godoc.org/gonum.org/v1/gonum/graph/iterator#OrderedNodes) implementation of the [iterator](https://godoc.org/gonum.org/v1/gonum/graph/iterator) package.

### CODE REVIEW

**Comment by chewxy** [comment]
I'll work on this after I finish submitting my last chapters to the publisher... sorry that it's taken solong

**Comment by leakyshoe** [comment]
Any news on this PR because it has been blocking us for a while now and from your "Dependencies" table "Development of Gorgonia is committed to keeping up with the most updated version"?

**Comment by chewxy** [comment]
Oops, I have a PR good to go on another machine. I thought I had closed this... sorry

**Comment by chewxy** [comment]
gimme a few hrs to close this

**Comment by leakyshoe** [comment]
Thanks but still broken, see https://github.com/gorgonia/gorgonia/issues/262

```go
gorgonia.org/gorgonia/walker.go:43:43: cannot use g (type *ExprGraph) as type graph.Directed in argument to topo.SortStabilized:
	*ExprGraph does not implement graph.Directed (wrong type for From method)
		have From(int64) []graph.Node
		want From(int64) graph.Nodes
```

```go
gorgonia.org/gorgonia/walker.go:53:33: cannot use g (type *ExprGraph) as type graph.Directed in argument to topo.Sort:
	*ExprGraph does not implement graph.Directed (wrong type for From method)
		have From(int64) []graph.Node
		want From(int64) graph.Nodes
```

**Comment by leakyshoe** [comment]
Well we just use gorgonia like this:

import "gorgonia.org/gorgonia"
import "gorgonia.org/tensor"

and in one place gonum like this

"gonum.org/v1/gonum/stat"

We are using Go modules

**Comment by leakyshoe** [comment]
so all master branch

**Comment by leakyshoe** [comment]
https://github.com/gonum/gonum/blob/master/graph/graph.go
```go
From(id int64) Nodes
```

https://github.com/gorgonia/gorgonia/blob/master/graph.go
```go
func (e edge) From() graph.Node { return e.from }
```

**Comment by chewxy** [comment]
Will investigate and get back to you in about 9 hrs

**Comment by chewxy** [comment]
I investigated last night.. the current build of Gorgonia in Master is built against the master branch of Gonum. I'm slightly lost

**Comment by leakyshoe** [comment]
Nope we just use the master direct from GitHub. 

"I'm slightly lost"
Well now and for the last few months the code in gonum for Graph defines this func in its interface "From(id int64) Nodes" see https://github.com/gonum/gonum/blob/master/graph/graph.go

but right now gorgonia defines this func in its implementation "func (e edge) From() graph.Node { return e.from }" see https://github.com/gorgonia/gorgonia/blob/master/graph.go

**Comment by chewxy** [comment]
They're different things though. Gorgonia's `*ExprGraph` implements https://godoc.org/gonum.org/v1/gonum/graph#Graph. The implementation can be found here: https://github.com/gorgonia/gorgonia/blob/master/graph.go#L536

`gorgonia.edge` implements this: https://godoc.org/gonum.org/v1/gonum/graph#Edge

**Comment by leakyshoe** [comment]
:(

**Comment by leakyshoe** [comment]
Well just tried again and

```shell
vendor/gorgonia.org/gorgonia/walker.go:43:43: cannot use g (type *ExprGraph) as type graph.Directed in argument to topo.SortStabilized:
	*ExprGraph does not implement graph.Directed (wrong type for From method)
		have From(int64) []graph.Node
		want From(int64) graph.Nodes
vendor/gorgonia.org/gorgonia/walker.go:53:33: cannot use g (type *ExprGraph) as type graph.Directed in argument to topo.Sort:
	*ExprGraph does not implement graph.Directed (wrong type for From method)
		have From(int64) []graph.Node
		want From(int64) graph.Nodes
```

**Comment by chewxy** [comment]
Is the build failing for you? If so could I have a look at the failing msg?

**Comment by leakyshoe** [comment]
and this is the mode file after re-initializing

```shell
	gonum.org/v1/gonum v0.0.0-20190128093212-dca16df66688
	gonum.org/v1/netlib v0.0.0-20190119082159-9be13e02fd56 // indirect
	gorgonia.org/cu v0.8.0 // indirect
	gorgonia.org/gorgonia v0.8.4
	gorgonia.org/tensor v0.8.1
	gorgonia.org/vecf32 v0.7.0 // indirect
	gorgonia.org/vecf64 v0.7.0 // indirect
```

**Comment by chewxy** [comment]
Hmmm This is an interesting problem

https://github.com/gorgonia/gorgonia/blob/master/graph.go#L536 indicates that the function has the correct type signature.

**Comment by chewxy** [comment]
OH! ... the current version is v0.9.0-beta

**Comment by leakyshoe** [comment]
Ah cool :)

**Comment by chewxy** [comment]
I am so so sorry... I've also just added a new release: https://github.com/gorgonia/gorgonia/releases/tag/v0.9.1

**Comment by chewxy** [comment]
the latest versions of all the packages are out of date in your mod file

**Comment by leakyshoe** [comment]
IC well that what we get if we initialize from scratch using go modules with:

```shell
go mod init `basename $(pwd)` && go mod tidy
go mod vendor
go get -u; go mod tidy && go mod vendor
```

**Comment by leakyshoe** [comment]
BTW thanks very much for putting the time in to helping me!

OK here are some attempts at using various tags, interesting that the 'walker.go' issue went away in version v0.9.1:

```shell
 go get -u gorgonia.org/gorgonia@v0.9.1
go: finding gorgonia.org/dawson v1.1.0
go: downloading gorgonia.org/dawson v1.1.0
# gorgonia.org/gorgonia
.../go/pkg/mod/gorgonia.org/gorgonia@v0.9.1/node.go:437:16: n.shape.CalcStrides undefined (type tensor.Shape has no field or method CalcStrides)
.../go/pkg/mod/gorgonia.org/gorgonia@v0.9.1/utils.go:147:28: undefined: tensor.InfChecker
.../go/pkg/mod/gorgonia.org/gorgonia@v0.9.1/utils.go:190:28: undefined: tensor.NaNChecker
```

```shell
go get -u gorgonia.org/gorgonia@v0.9.0-beta
go: finding gorgonia.org/gorgonia v0.9.0-beta
go: downloading gorgonia.org/gorgonia v0.9.0-beta
# gorgonia.org/gorgonia
.../go/pkg/mod/gorgonia.org/gorgonia@v0.9.0-beta/node.go:436:16: n.shape.CalcStrides undefined (type tensor.Shape has no field or method CalcStrides)
.../go/pkg/mod/gorgonia.org/gorgonia@v0.9.0-beta/utils.go:137:28: undefined: tensor.InfChecker
.../go/pkg/mod/gorgonia.org/gorgonia@v0.9.0-beta/utils.go:180:28: undefined: tensor.NaNChecker
.../go/pkg/mod/gorgonia.org/gorgonia@v0.9.0-beta/walker.go:43:43: cannot use g (type *ExprGraph) as type graph.Directed in argument to topo.SortStabilized:
	*ExprGraph does not implement graph.Directed (wrong type for From method)
		have From(int64) []graph.Node
		want From(int64) graph.Nodes
.../go/pkg/mod/gorgonia.org/gorgonia@v0.9.0-beta/walker.go:53:33: cannot use g (type *ExprGraph) as type graph.Directed in argument to topo.Sort:
	*ExprGraph does not implement graph.Directed (wrong type for From method)
		have From(int64) []graph.Node
		want From(int64) graph.Nodes
```


```shell
go get -u gorgonia.org/gorgonia@v0.8.4
# gorgonia.org/gorgonia
.../go/pkg/mod/gorgonia.org/gorgonia@v0.8.4/walker.go:43:43: cannot use g (type *ExprGraph) as type graph.Directed in argument to topo.SortStabilized:
	*ExprGraph does not implement graph.Directed (wrong type for From method)
		have From(int64) []graph.Node
		want From(int64) graph.Nodes
.../go/pkg/mod/gorgonia.org/gorgonia@v0.8.4/walker.go:53:33: cannot use g (type *ExprGraph) as type graph.Directed in argument to topo.Sort:
	*ExprGraph does not implement graph.Directed (wrong type for From method)
		have From(int64) []graph.Node
		want From(int64) graph.Nodes
```

```shell
go get -u gorgonia.org/gorgonia@v0.8.0
go: finding gorgonia.org/gorgonia v0.8.0
go: downloading gorgonia.org/gorgonia v0.8.0
# gorgonia.org/gorgonia
.../go/pkg/mod/gorgonia.org/gorgonia@v0.8.0/walker.go:43:43: cannot use g (type *ExprGraph) as type graph.Directed in argument to topo.SortStabilized:
	*ExprGraph does not implement graph.Directed (wrong type for Edge method)
		have Edge(graph.Node, graph.Node) graph.Edge
		want Edge(int64, int64) graph.Edge
.../go/pkg/mod/gorgonia.org/gorgonia@v0.8.0/walker.go:53:33: cannot use g (type *ExprGraph) as type graph.Directed in argument to topo.Sort:
	*ExprGraph does not implement graph.Directed (wrong type for Edge method)
		have Edge(graph.Node, graph.Node) graph.Edge
		want Edge(int64, int64) graph.Edge
```

**Comment by chewxy** [comment]
Yeah. That's because I had just literally made the new release v0.9.1 today. And I wouldn't have merged this branch if you hadn't reminded me. So really, thank you.

**Comment by leakyshoe** [comment]
Then if I remove all references to gorgonia and gonum and then manually add the following it works :)
So I guess

```go
	gorgonia.org/cu v0.9.0-beta
        gorgonia.org/dawson v1.1.0 
	gorgonia.org/gorgonia v0.9.1
	gorgonia.org/tensor v0.9.0-beta
```

**Comment by leakyshoe** [comment]
If I don't manually pin those and only use "gorgonia.org/gorgonia v0.9.1" then I end up with this in go.mod which gives the error below

```shell
	gorgonia.org/cu v0.8.0 // indirect
	gorgonia.org/dawson v1.1.0 // indirect
	gorgonia.org/gorgonia v0.9.1
	gorgonia.org/tensor v0.8.1
	gorgonia.org/vecf32 v0.7.0 // indirect
	gorgonia.org/vecf64 v0.7.0 // indirect

```

```shell
vendor/gorgonia.org/gorgonia/node.go:437:16: n.shape.CalcStrides undefined (type tensor.Shape has no field or method CalcStrides)
vendor/gorgonia.org/gorgonia/utils.go:147:28: undefined: tensor.InfChecker
vendor/gorgonia.org/gorgonia/utils.go:190:28: undefined: tensor.NaNChecker
```

**Comment by leakyshoe** [comment]
So in summary this works

1. Remove all references to gorgonia and gonum from go.mod
2. Delete go.sum
3. Add this to go.mod
    gorgonia.org/cu v0.9.0-beta
    gorgonia.org/gorgonia v0.9.1
    gorgonia.org/tensor v0.9.0-beta
4. Run "go get -u; go mod tidy && go mod vendor"

**Comment by chewxy** [comment]
Gorgonia will have proper gomod support in the coming few days.

**Pull request merged**
