### PR TITLE
Upsample2d simplest realization

### PR DESCRIPTION
**Pull request by cpllbstr**
This operator has the same output as Pytorch upsample with nearest mode.

### CODE REVIEW

**Comment by LdDl** [comment]
Yeah, it's good to have such operation for popular object detection architectures such as YOLO/SSD.

**Comment by chewxy** [comment]
checking. @cpllbstr can you send me an email: chewxy [at] gmail.com with the title Gorgonia Contributor 2020

**Comment by chewxy** [comment]
grr Travis is having issues... gimme a few seconds

**Comment by chewxy** [comment]
Concurrency is hard...  fcf0611  happens after 34b2bdd. But in Travis, the job ID for fcf0611 is 1058 and 34b2bdd's job ID is 1059. 

Conclusion: don't treat job IDs as monotonically increasing.

**Pull request merged**
