### PR TITLE
Attempt to reproduce a reshape bug

### PR DESCRIPTION
**Pull request by chewxy**

### CODE REVIEW

**Comment by chewxy** [comment]
My reaction to this as I am reading this for the first time: WTF?

**Comment by chewxy** [comment]
Not sure if this is really a bug. I understand the issue now.  It happens in the back propagation phases. 

The error is as such:

```
 Input shape is (100, 3136). Expected (100, 64, 7, 7)
```
They're the same exact sizes (64 * 7 * 7 = 3136). This may be an overzealous checker

**Comment by chewxy** [comment]
line 1159 in `op_tensor.go`. I gotta rethink this for a bit.

**Comment by dcu** [comment]
wouldn't checking the total size do the trick?

**Comment by chewxy** [comment]
I believe #457 fixes this

**Pull request closed without merging**
