### PR TITLE
feat: add custom runner for arm64

### PR DESCRIPTION
**Pull request by blackrez**
Add custom runner for arm

### CODE REVIEW

**Comment by blackrez** [comment]
@chewxy @owulveryck Do we open issues for fixe the tests on arm before merge this PR ?

**Review by owulveryck — APPROVED** [review]
LGTM

**Comment by blackrez** [comment]
The runner is ready to test the code. But some tests are still failing on ARM64.

**Comment by chewxy** [comment]
Failing tests are due to numerical issues. Not a deal breaker. Merging.

**Pull request merged**
